version: '3'
services: 
    web-server:
        build:
            context: ./
            dockerfile: Dockerfile
        tty: true
        environment:
            PORT: 5000
            VERSION: v2
            DSN: web-server:bAssKLjmYnQf3!bJGy6BJ@@tcp(mysql:3306)/web_server_db?charset=utf8mb4&parseTime=True&loc=Local
        ports:
            - "5000:5000"
        networks:
            - docker-network
    mysql:
        image: mysql:8.0
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: true
        networks:
            - service-network
        volumes:
            - "./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql"
            - "mysql_database:/var/lib/mysql"
networks:
    service-network:
        driver: bridge
volumes:
  mysql_database:
    driver: local